services:
  api:
    container_name: nestjs-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Estos nombres DEBEN coincidir con los de tu configService.get()
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=hostal
    volumes:
      - .:/app               # ← monta todo tu código local
      - /app/node_modules    # ← protege node_modules del host
    command: pnpm run start:dev
    networks:
    - hostal-net
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hostal
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - hostal-net

networks:
  hostal-net:
    driver: bridge

volumes:
  mariadb_data: